# Tender (color theme)
# [[plugins]]
# repo = 'jacoborus/tender.vim'

# vim-code-dark (VS Code風カラーテーマ）
[[plugins]]
repo = 'tomasiser/vim-code-dark' 

# solarized (theme)
#[[plugins]]
# repo = 'altercation/vim-colors-solarized'

# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coil398#init#coc#hook_source()'

# fern
[[plugins]]
repo = 'lambdalisue/fern.vim'

# git-status for fern
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

# nerdfont for fern
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

# fern preview
[[plugins]]
repo = 'yuki-yano/fern-preview.vim'

# devicons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# quick-scope
[[plugins]]
repo = 'unblevable/quick-scope'

# fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'

# committia
[[plugins]]
repo = 'rhysd/committia.vim'

# theme for alirline
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
        let g:airline_theme = 'powerlineish'
'''

# airline
[[plugins]]
repo = 'vim-airline/vim-airline'
#depends =['vim-airline/vim-airline-themes', 'tpope/vim-fugitive']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#buffer_nr_show = 1
    let g:airline#extensions#branch#enabled=1
    let g:airline#extensions#hunks#enabled=0
    if !exists('g:airline_symbols')
        let g:airline_symbols = {}
    endif
    let g:airline_section_a = airline#section#create(['mode', 'crypt'])
'''

# fzf
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'

# gitgutter
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
        set signcolumn=yes
        let g:gitgutter_async = 1
        let g:gitgutter_sign_modified = 'rw'
        highlight GitGutterAdd ctermfg=green
        highlight GitGutterChange ctermfg=yellow
        highlight GitGutterDelete ctermfg=red
        highlight GitGutterChangeDelete ctermfg=yellow
'''

# tcomment
[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    vnoremap ? :'<,'>TComment<CR>
'''

# Colorize brackets pair
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
        let g:rainbow_active = 1
'''

# Buffer Line
[[plugins]]
repo = 'akinsho/bufferline.nvim'

